import type { Metadata } from "next";
import { Poppins } from "next/font/google"; 
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],  
});

export const metadata: Metadata = {
  title: "Simius",
  description: "Generated by create next app",
  icons: {
    icon: "/simius.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
